2
Dup4/starter-nestjs pull request #10
Opened 2024-02-07 15:17 UTC by xyzyx0314

2

2024-02-07 15:26 UTC, Dup4 requested changes

2024-02-07 15:26 UTC, Dup4 commented on ${APPDATA}/npm/na
> +#!/bin/sh
这个文件夹里的东西，应该没必要 commit 上来？

2024-02-07 18:54 UTC, xyzyx0314 reviewed
应该是这版实现增删改查吧，前面传上去的不知道哪个配置文件不一样，本地跑不了了，应该是app.module.ts内多出了一个什么东西。http://172.18.55.115:3000/api/docs#/这里的post好像不能输入？

2024-02-08 00:12 UTC, Dup4 requested changes

2024-02-08 00:12 UTC, Dup4 commented on src/user.service.ts
> +      // 判断是否有搜索条件
不要写中文注释，如有必要，请写英文注释

2024-02-08 00:12 UTC, Dup4 commented on src/user.service.ts
> +      // console.log("success");
不必要的代码请直接移除

2024-02-08 00:12 UTC, Dup4 commented on src/app/app.controller.ts
> +  @Post("user")
是不是应该直接搞一个 `user.controller.ts`，而不是直接将这几个接口放在 `app.controller.ts` 下面

2024-02-08 00:12 UTC, Dup4 commented on prisma/migrations/migration_lock.toml
> +provider = "sqlite"
应该用 MySQL 而不是 sqlite

2024-02-27 01:03 UTC, closed without merging