20240219v1
Dup4/starter-nestjs pull request #13
Opened 2024-02-18 20:12 UTC by xyzyx0314

搞了远程数据库改成mysql后，本地能跑了，但是后面检测一堆问题，改着改着就改的挺奇怪的，退回之前重新试下

2024-02-18 20:28 UTC, xyzyx0314 commented
最后好像又变成那版的情况，换成mysql后Lint那里又是一堆报错（大部分报错代码都可以删掉，因为只需要用户功能，不需要发帖什么的，而且有些感觉删掉过），那边那版是后面好像更新了个pnpm-lock.yaml然后开始错的奇奇怪怪就最后几次那种报错吧

2024-02-19 00:59 UTC, Dup4 requested changes

2024-02-19 00:59 UTC, Dup4 commented on dev.db
这个文件删掉

2024-02-19 00:59 UTC, Dup4 commented on nohup.out
这个文件删掉

2024-02-19 00:59 UTC, Dup4 commented on .env
> +DATABASE_URL="mysql://CKZ:CKZ1!mysql@60.204.251.220:3306/testuser"
你把你的 DB 的链接信息都推到 git 上来了

可以在 `.gitignore` 文件里面把 `.env` 这个文件过滤掉
如果不知道 `.gitignore` 有什么用可以看这个：https://git-scm.com/docs/gitignore

然后创建一个 `example.env` 文件，里面的内容可以是：

```bash
DATABASE_URL="your DB URL"
```

作用主要是告诉其它人，`.env` 文件里可以有哪些环境变量

2024-02-19 00:59 UTC, Dup4 commented on ${APPDATA}/npm/na
> +#!/bin/sh
`${APPDATA}` 这个目录下的文件很奇怪，是必须要存在的吗？

如果你直接删掉这个文件夹会怎么样？

如果是由于你在 Windows 上开发所必须存在的文件，那么请你在 `.gitignore` 中过滤掉这个文件夹

如果不知道 `.gitignore` 有什么用可以看这个：https://git-scm.com/docs/gitignore

2024-02-19 09:30 UTC, Dup4 commented on prisma/schema.prisma
> +  output   = "../node_modules/.prisma/client"
你把这个改成 `./client` 试试？

2024-02-19 09:31 UTC, Dup4 commented on prisma/schema.prisma
> +  output   = "../node_modules/.prisma/client"
因为 `node_modules` 是被 ignore 掉的

2024-02-19 11:12 UTC, Dup4 commented
哦，我知道了，不应该把 client 文件给放到 git 上
而是应该在在 after install 之后生成一下 prisma client 的文件

2024-02-19 11:14 UTC, Dup4 commented
你是怎么生成 prisma client 那些文件的，可以把这个命令放在 `package.json` 的 scripts.postinstall 字段里面

https://docs.npmjs.com/cli/v10/using-npm/scripts#npm-install

2024-02-19 11:30 UTC, Dup4 commented
`"pnpm install @prisma/client"` 这一行命令可以生成 client 那些文件吗？

2024-02-19 11:45 UTC, xyzyx0314 commented
我刚才试了一下是用npx prisma migrate dev --name init会在 prisma 文件夹下面产生一个 client 文件夹，因为现在  output   = "./client" 这句话应该是指定了一个生成的位置？但是这个 client 似乎也是被我传上来了
npx prisma init 应该只是生成了 schema.prisma 和 .env  这俩个文件吧

2024-02-21 10:07 UTC, Dup4 commented on .env
> +# Environment variables declared in this file are automatically made available to Prisma.
这个文件怎么还在

2024-02-21 10:08 UTC, Dup4 commented on .vscode/settings.json
> +  "debug.javascript.resourceRequestOptions": {}
这一行有什么用吗？没用的话去掉

2024-02-21 10:08 UTC, Dup4 commented on .vscode/tasks.json
> +{
话说你是用了什么功能，生成了这个文件？

2024-02-21 10:59 UTC, Dup4 commented on .env
> +DATABASE_URL="your DB URL"
你应该让这个文件从 git 上消失，只存在于你本地，而不是改掉这个变量的值，不然你本地怎么连？

2024-02-21 11:01 UTC, xyzyx0314 commented
刚才试了一下.env不上传,然后传了example.env,就错了,因为连不上,所以我想看看如果是.env内的your DB URL会怎么样

2024-02-27 01:03 UTC, Dup4 requested changes

2024-02-27 01:03 UTC, Dup4 commented on src/user/dto/user-response.dto.ts
> +  email: string = "请输入邮箱";
这个应该是 default value 而不是 placeholder 吧？

那我觉得如果请求里面没带这个参数，应该过不了参数检验，不应该放一个默认值

2024-02-28 14:02 UTC, Dup4 approved these changes

2024-02-28 14:03 UTC, merged